package decimal.apigateway.enums;

public enum RequestValidationTypes {

    HEADERS, REQUEST, SESSION, SERVICE_NAME, IP, API_AUTHORIZATION, SERVICE_SCOPE, TXN_KEY, CLIENT_SECRET, HASH, APPLICATION, INACTIVE_SESSION, PUBLIC_JWT_TOKEN

}
